* Background
  - Article written by H.R. McMaster [[https://thestrategybridge.org/the-bridge/2016/2/26/eagle-troop-at-the-battle-of-73-easting][Eagle Troop at the Battle of 73
    Easting]] - LESSONS FOR TODAY'S SMALL UNIT LEADERS

* Simple Summary

1) *Lead from the front.*
2) *Shoot first.*
3) *Fight through the fog of battle.*
4) *Follow your instincts and intuition.*
5) *Use standard unit fire and battle drills.*
6) *Foster initiative.*
7) *Use tanks to take the brunt of battle.*
8) *Be prepared for misfires and degraded operations.*
9) *Coordinate between platoons and ensure mutual support.*
10) *Take risk to win.*

* Comphrensive Summary

1) *Lead from the front.* Leaders must be forward to gain a clear
   picture and make decisions. As Sergeant Harris engaged with 25mm,
   Lieutenant Gauthier moved forward to assess and further develop the
   situation. Gauthier fired a TOW missile into the center of the
   enemy position in the village to orient our tanks. After our
   gunner, Staff Sergeant Craig Koch, fired a subsequent tank round to
   mark center, all nine tanks fired high explosive rounds into the
   village simultaneously to suppress the enemy position.  Despite the
   secondary explosions in the village to its south, First Platoon
   maintained its primary observation to the east.

2) *Shoot first.* If you know where friendly forces are and there is not
   a danger of civilian casualties, do not hesitate to shoot or
   conduct reconnaissance by fire. The side that shoots first has a
   tremendous advantage. Staff Sergeant David Lawrence was the
   commander of First Platoon's northernmost Bradley. When his gunner,
   Sergeant Bradley Feltman, said, "Hey, I've got a hot spot out
   there; I'm not sure what it is," Lawrence responded, "Put a TOW in
   it; see what it is." Lawrence identified the hot spot as a T-72 as
   the turret was ripped from its hull in the ensuing explosion. Our
   troop's experience was consistent with Erwin Rommel's observation
   in his World War I book, Infantry Attacks: "I have found again and
   again in encounter actions the day goes to the side that is first
   to plaster its opponents with fire."

3) *Fight through the fog of battle.* Be prepared for confusion and
   concurrent activity. As we suppressed enemy positions in the
   village and while Lawrence was launching a missile, the Troop
   received permission to advance to the 70 Easting. I instructed
   First Platoon to resume movement east. Lieutenant Petschek did not
   respond immediately because Lawrence was reporting on the platoon
   radio net, "Contact! Contact, east, tank!" Simple orders and
   complete reports are essential to maintaining common understanding
   in battle.

4) *Follow your instincts and intuition.* As Sergeant Feltman launched
   the TOW missile, I decided to go to a tanks lead formation and
   instructed Green and White, the tank platoons, to "follow my move."
   First Platoon pulled in behind as the tank wedge moved forward and
   covered the tanks' rear. Third platoon retained responsibility for
   flank security. As we began moving forward, First Platoon,
   responding to the contact report on their platoon radio net, began
   firing twenty-five millimeter high explosive munitions across the
   front. It was a little unnerving for the tanks as we moved
   forward. I gave First Platoon a cease-fire order-- "Red 1, this is
   Black 6, cease fire."  The two tank platoons were slightly
   delayed. As our tank came over the crest of the imperceptible rise
   north of the village, Sergeant Craig Koch, the gunner, reported
   "tanks direct front," I counted eight T-72s in prepared
   positions. They were at close range and visible to the naked eye.

5) *Use standard unit fire and battle drills.* Aim to overwhelm the
   enemy upon contact and retain the initiative through speed of
   action. As Sergeant Koch fired the main gun and destroyed the first
   tank, I sent a contact report to the troop, "This is
   Black 6. Contact east. Eight armored vehicles. Green and White, are
   you with me?" Sergeant Koch destroyed two more tanks as our tank
   platoons accelerated movement. All nine tanks began engaging
   together as we advanced. In approximately one minute, everything in
   the range of our guns was in flames. Fire distribution and control
   allowed us to destroy a much larger enemy force in a very short
   period of time.

6) *Foster initiative.* Every trooper understood how our platoons and
   the troop conducted fire and maneuver. Our tank driver, Specialist
   Christopher Hedenskog knew that he had to steer a path that
   permitted both tank platoons to get their guns into the fight. He
   turned 45 degrees to the right and kept our frontal armor toward
   the first enemy tanks we engaged.  He drove through a minefield,
   avoided the anti-tank mines, reporting on the intercom, "Sir, I
   think you need to know, we just went through a minefield." He knew
   that it would be dangerous to stop right in the middle of the enemy
   kill zone. Hedenskog saw that our tank platoons had a window of
   opportunity to shock the enemy and take advantage of the first
   blows that Sergeant Koch had delivered.

7) *Use tanks to take the brunt of battle.* Tanks drove around the
   anti-tank mines and Bradleys and other vehicles followed in their
   tracks. Our Squadron S-3's tank, commanded by Major Douglas
   MacGregor, hit an anti-tank mine, but the blast damaged the tank
   only slightly. It continued the attack and made a rapid repair when
   we halted.  We ran over anti-personnel mines, but they sounded like
   microwave popcorn popping and had no effect on armored
   vehicles. The rate of fire of our tanks allowed enemy tanks to fire
   only two errant main gun rounds at the outset of the battle and two
   later as the troop assaulted.  Enemy machine gun fire had no effect
   on the troop's advance. The psychological shock of our tanks
   advancing undaunted toward their defensive positions paralyzed and
   panicked the enemy.

8) *Be prepared for misfires and degraded operations.* Lieutenant Jeff
   DeStefano's tank crew came around the village, destroyed an enemy
   tank, and acquired a second tank at very close range that was
   traversing on them. A round got stuck in the breech of DeStefano's
   canon. The loader grabbed hold of the loader's hatch, kicked the
   round in, the breech came up, and the gunner, Sergeant Matthew
   Clark, destroyed the T-72.  In another example, Staff Sergeant
   Digbie ordered Private First Class Charles Bertubin to reload TOW
   missiles. Bertubin could not get the cargo hatch open,
   however. When the lightweight wrestler kicked the hatch release, he
   sheared it off. Rather than tell his Bradley commander that he
   could not get the TOWs reloaded, he jumped out of the back door
   while the vehicle was under small arms and machinegun fire. He
   climbed onto the back of the Bradley, loaded both missiles, then
   tapped his Bradley commander on the shoulder while yelling, "TOWs
   are up." Staff Sergeant Digbie nearly jumped out of skin because he
   thought that an Iraqi had climbed onto the Bradley.

9) *Coordinate between platoons and ensure mutual support.* The
   burning tanks and personnel carriers of the enemy's first defensive
   line formed a curtain of smoke that concealed enemy further to the
   east. As our tanks assaulted through the smoke, we saw other enemy
   armored vehicles and large numbers of infantry running to get back
   to subsequent trench lines and positions. We destroyed the enemy
   armored vehicles quickly and shot the infantry with machine guns as
   we closed the distance with them.  Pockets of enemy soldiers threw
   their arms up. Our soldiers were disciplined; turrets turned away
   from any enemy soldier with his hands raised. Tank platoon leaders
   asked scout platoons to pick up observation of the enemy infantry
   as their Bradleys came through the smoke. The scouts saw that the
   enemy had used false surrender to gain a better position. Enemy
   soldiers were re-shouldering their rifles and rocket propelled
   grenades (RPGs). Our Bradleys surprised the enemy and killed them
   before they could engage our tanks effectively.

10) *Take risk to win.* Because Eagle Troop pressed the assault, the
    enemy could not respond effectively. As we cleared the westernmost
    defensive positions, our executive officer, Lieutenant John
    Gifford, broke in on the radio, "I know you don’t want to know
    this right now, but you’re at the limit of advance; you’re at the
    70 Easting." I responded, "Tell them we can’t stop. Tell them
    we’re in contact and we have to continue this attack. Tell them
    I’m sorry." We had surprised and shocked the enemy; stopping would
    have allowed them to recover. As Erwin Rommel observed in Infantry
    Attacks: "The man who lies low and awaits developments usually
    comes off second best. .. .It is fundamentally wrong to halt—-or
    to wait for more forces to come up and take part in the action."
    Eagle Troop continued to attack toward another very subtle
    ridgeline on which the enemy positioned his reserve, a coil of
    eighteen T-72 tanks. Major Mohammed later told one of our troopers
    that he had not known he was under attack until a soldier ran into
    his elaborate command bunker yelling, "tanks, tanks!" By the time
    he got to his observation post, all the vehicles in defensive
    positions to the west were in flames. He ordered the reserve
    behind him to establish a second defensive line. It was too
    late. Eagle Troop's tanks crested the rise and entered their
    assembly area. The tanks were starting to move out when we
    destroyed them at close range.

