* Background
  - Key points taken from the book:
    Conquering Crisis: Ten Lessons to Learn Before You Need Them


* Overview
- Framework described as the following in a circle:

  Assess -> Report -> Contain -> Shape -> Manage
  And inside it says RESOLVE

#+begin_src mermaid
    graph TD
    subgraph Resolve
        Assess --> Report;
        Report --> Contain;
        Contain --> Shape;
        Shape --> Manage;
        Manage --> Assess;
    end

    style Assess fill:#f9f,stroke:#333,stroke-width:2px
    style Report fill:#ccf,stroke:#333,stroke-width:2px
    style Contain fill:#9cf,stroke:#333,stroke-width:2px
    style Shape fill:#c9f,stroke:#333,stroke-width:2px
    style Manage fill:#f9c,stroke:#333,stroke-width:2px  
#+end_src
 
* 1) First Reports Are Always Wrong

1. Be very skeptical of first reports.  Take time to verify the facts.
2. Be cautious about making a declarative statement in the first
   communication up the chain or publicly.
3. Have a corporate procedure for evaluating the quality of the
   information that is received during the first hours of a crisis.

* 2) Have a Council of Colonels

1. Use the existing chain of command and your established staff to
   provide you valuable insights on resolving the crisis, but don’t
   hesitate to have a group of trusted advisors (your Council of
   Colonels) outside the C-suite or the usual circle that can give you
   the unvarnished truth about the organization and your leadership
   decisions.
2. While your Council of Colonels can be essential to your decision
   process, do not exclude others on your staff from being privy to
   the nature of the discussions.
3. Use the Council of Colonels sparingly. Resentment will come quickly
   if the Council of Colonels too often usurps the normal staffing
   process.

* 3) Bad News Doesn't Get Better with Age

1. Never delay getting bad news to your bosses.
2. Remember, tell the truth, the whole truth, and nothing but the
   truth. Delaying bad news or misrepresenting the truth will erode
   trust and credibility between you and your boss or you and the
   public.
3. Acknowledge the severity of the incident, accept responsibility,
   and have a plan for addressing the crisis.

* 4) Weaponize the Truth

1. Use truth and transparency through the crisis to show that you
   understand the problem and that you are taking concrete steps to
   resolve the issue. It may be uncomfortable, demoralizing to the
   organization, and personally embarrassing, but deception and
   opaqueness are a whole lot worse.
2. Stand in full view of the public eye, take the hard questions,
   accept the criticism, and answer truthfully. Get all the negative
   reporting behind you so you can begin to move forward.
3. If there are whistleblowers who generated the crisis, praise them
   for their courage. Any attempt to suppress criticism from within
   will only result in a public backlash.

* 5) Move All Your Option Forward

1. Push all your options as close to the crisis as possible. This will
   allow you to maintain your decision space and move quickly when
   necessary.
2. Move a trusted, competent professional to the crisis site as
   quickly as possible and be prepared to deploy your people to every
   location that might be affected by the crisis. This will allow you
   to stay abreast of events as they unfold.
3. Have a prerehearsed plan for rapidly mobilizing your people and
   your resources. The nature of the crisis may come as a surprise,
   but the speed of your response should not.

* 6) Trust the Second Law of Thermodynamics

1. You must take decisive steps to contain a crisis. Left alone, a
   crisis will get worse, not better.
2. The longer you delay in taking decisive action, the harder the
   decision and the action become.
3. There is always a difficult balance between rushing to failure and
   being slow to act. If you have to choose one or the other—act.

* 7) Don't Rush to Failure

1. Plan for the outcome you want to achieve.
2. Use all the decision space you have before taking action, but no
   more.
3. Time is your most perishable resource. Use it wisely.

* 8) Micromanagement Is Not an Ugly Word

1. Check now to ensure your company’s contingency planning is
   current. Preparation is the key.
2. At the beginning of a crisis, be exacting in your
   communications. Leave no doubt about precisely what you want done
   and how you intend to shape the outcome.
3. Monitor the crisis closely. As the conditions change, you may need
   to adjust your guidance to fit the situation on the ground.

* 9) Dictate the Tempo

1. Don’t try to solve all the problems at once. Identify the most
   vulnerable aspect of the crisis, the one you can affect the
   quickest.
2. Next, slow the pace of the crisis with one strong, decisive move
   directed at the fastest moving concern.
3. Finally, reinforce your actions with a resource-heavy approach to
   dictate the tempo and shape the outcome.

* 10) There Is Always Time for a Morale Check

1. Spend time with the rank and file during a crisis. They are looking
   for your guidance and your inspiration. If their morale is high,
   you will get through the crisis much more quickly.
2. Appearances matter. In a public forum, always look confident. But
   it’s a crisis for a reason, and maybe that reason is you—so be
   equally gracious and humble.
3. Your morale matters. Have someone you trust who can boost your
   spirits when disaster strikes; someone who can help you manage your
   physical well-being and your mental toughness, and who can maintain
   your sense of humor.
